language: android
jdk: oraclejdk8
sudo: false
global:
- ANDROID_API=27
- EMULATOR_API=21
- ANDROID_BUILD_TOOLS=27.0.3
- ADB_INSTALL_TIMEOUT=5
android:
components:
- tools
- platform-tools
- build-tools-$ANDROID_BUILD_TOOLS
- android-$ANDROID_API
- android-$EMULATOR_API
- extra-google-m2repository
- extra-android-m2repository
- sys-img-armeabi-v7a-android-$ANDROID_API
- sys-img-armeabi-v7a-android-$EMULATOR_API
- extra-android-m2repository
- extra-android-support
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_install:
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: VQCGcgZ/AbFTrWP/o/MzfnBtzZEZHkeCXh2F2UYQU0WSgMiP+JzymsR2vezxvFGmAqLRZTouAD3VnHZxfKHkQ4BNwD6gKjyNWnb3U7FRcsy65JP7qvTe9mFME6lO+HUcWPbKZLA+H8vk+FR6QHpBBCYilmXxTJC+oKFe1nlKVOlFZbuSlIF5QthE/hbHIq39SO0SQa5+ZP5o6VAWcK2QjDNL+G6Bhx14MccBhJONSoEauMagsCkv1RbR8/fm2IVjBvh6GVTm+po+ZO21AahjPaaKApgLBo0MFIzpNvDmBfhdJY0MYPEmUELWF/ki9CMx6KA7ZyTXOhwos3HTRh0bjL8q94tyJRKgQki52hvz25HEJMqkEUnvcUezS+kxByRGgENnbZ/gDh1Gi20g++/hwuYfEevdkigtKkjjaf+Q10JINlomRsK9pNk9Sb0CC5Qw1UdQoTEVeXq2E8Craxvdj1DZB2Zg1hst2DGUw4JcgYlokYLsGbt5WdWAU6vOJy0JFNQNwz9YERODRRWSoYckhhwnOEblsFeLBoEaoU5Msz0KlXQ66zbJoUKtHD42yARQnlBI/6oShVpuw9kTcG7fiUDp9pxwhPr5UQy/BM6oClYtBXXAgCaiTdSNQRQYneu2M/5qlaYeI9JLtBxZKYFzm6B6EVGCxzLd+nq1cr2W9AA=
  file: app/build/outputs/apk/release/*
  skip_cleanup: true
  on:
    tags: true
    api_key: ${GH_TOKEN}
    repo: caiyonglong/MusicLake
    branch: develop

